---
include:
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-docker.yml"
  - project: "Bigouden/gitlab-ci-templates"
    file: ".gitlab-ci-prometheus.yml"

.services:
  services:
    - name: $CONTAINER_FAIL2BAN
      alias: fail2ban
    - name: $CONTAINER_TEST_IMAGE
      alias: exporter
      variables:
        FAIL2BAN_SOCAT_HOST: "fail2ban:12345"
        FAIL2BAN_SOCAT_FILE: "/tmp/fail2ban.sock"
        FAIL2BAN_EXPORTER_SOCKET: "/tmp/fail2ban.sock"
  image: $CONTAINER_CLIENT_IMAGE
  before_script:
    - apk add --no-cache --update curl bind-tools
    # Bypass for curl & c-ares
    - echo "$(host -t A exporter | awk '/has address/ { print $4 }') exporter" >> /etc/hosts

  variables:
    GIT_STRATEGY: none
  dependencies: []

.services_owasp_zap:
  services:
    - name: $CONTAINER_FAIL2BAN
      alias: fail2ban
    - name: $CONTAINER_TEST_IMAGE
      alias: target
      variables:
        FAIL2BAN_SOCAT_HOST: "fail2ban:12345"
        FAIL2BAN_SOCAT_FILE: "/tmp/fail2ban.sock"
        FAIL2BAN_EXPORTER_SOCKET: "/tmp/fail2ban.sock"
  image:
    name: $CONTAINER_OWASP_ZAP_IMAGE
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  dependencies: []

variables:
  PROMETHEUS_EXPORTER_PORT: "8123"
  PROMETHEUS_EXPORTER_SCHEME: "http"
  CI_DEBUG_SERVICES: "true"
  CONTAINER_FAIL2BAN: $CI_REGISTRY/bigouden/alpine-fail2ban:daily
  FF_NETWORK_PER_BUILD: 1

stages:
  - Quality
  - Security
  - Build
  - Test
  - Inspect
  - Release
  - Clean
